### ISSUE TITLE
milestones

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pacopy#5]
Would it be useful to add an optional argument to `natural` and `euler_newton` to force solution at certain values of _&lambda;_ ?

It's easy enough now to reproduce, as in `test/test_bratu1d.py`, most of the left plot in figure 1.1 of ‘Deflation techniques…’ ([Farrell, Birkisson, & Funke](https://arxiv.org/abs/1410.5620)), but not the blue or red cross at _&lambda;_ = 2 or the right plot with the corresponding solutions _u_ (_x_; _&lambda;_ = 2).

[`scipy.integrate.solve_ivp`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html#scipy.integrate.solve_ivp) has a couple of related features: 
* `t_eval`: ‘Times at which to store the computed solution’
* `events`: ‘defined by a continuous function of time and state that becomes zero value in case of an event’

I envisage something like replacing

https://github.com/nschloe/pacopy/blob/1973500e422132f035fd9a419340c5100d6bb904/pacopy/natural.py#L79

with 

```python
milestone = next(milestones)
...
while ...:
    lmbda_next = lmbda + lmbda_stepsize
    if milestone < lmbda_next:
        lmbda = milestone
        milestone = next(milestones)
    else:
        lmbda = lmbda_next
```

plus handing:
* `lmbda_stepsize` might be negative
* `milestones` might be empty
 
The motivation is a steady Navier–Stokes solver for which the solutions are desired at certain Reynolds numbers.

**Comment by nschloe** [comment]
Interesting suggestion, and it's it looks certainly easy to implement. Would expect the continuation to _stop_ once a milestone is reached, or to continue?

**Comment by gdmcbain** [comment]
For natural parameter continuation, an obvious use-case is a strictly monotonic list of _&lambda;_ at the end of which the job's done.

In the general, e.g. arc-length, case, it's much less clear. I can't see as much practical call for milestones, except in making a figure like Farrell's, where one probably would like _&lambda;_ to have a nice round value to keep the caption tidy and to facilitate reproducibility.  Stopping at milestones is going to be trickier when the parameter isn't monotonic. Maybe defer that case; I don't really need to reproduce figure 1.1 but do need to sweep Reynolds number. 

On the question of termination, what I did to stop the 1-d Bratu arclength continuation after the curve had left the frame was raise an exception from the callback based on the norm. This sped things up a bit. kinnala/scikit-fem#126

**Comment by gdmcbain** [comment]
I came across a good motivation for stopping at milestones in natural parameter continuation in the literature:

> The backward step flow was formulated and solved as a steady flow problem. In order to obtain a solution for the specified Re of 800, a series of steady state solutions were obtained at intermediate Re-values of 200, 400 and 600. Zeroth-order continuation was used to advance from one Re solution to another. The indicated sequence of steps in Re does not represent an optimized path to the final required state but was selected for convenience and with a view towards comparing solutions at other standard conditions.

* Gartling, D. K. (1990). A test problem for outflow boundary conditions—flow over a backward‐facing step. _International Journal for Numerical Methods in Fluids_, 11, 953–967. [doi: 10.1002/fld.1650110704](https://dx.doi.org/10.1002/fld.1650110704)
