### ISSUE TITLE
default maximum parameter stepsize

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pacopy#8]
The default maximum parameter stepsize is finite

https://github.com/nschloe/pacopy/blob/b5ae74c2c17349a04165291e2e74fbc865da660b/pacopy/natural.py#L12

and small, depending on the system.  A couple of times I have forgotten this and removed the explicit setting, hoping for a faster run through the milestones #6 (Δλ ~ 10², in the example given there, kinnala/scikit-fem#145), only to have it tiptoe at Δλ = 1.

What about defaulting to no limit as for

https://github.com/nschloe/pacopy/blob/b5ae74c2c17349a04165291e2e74fbc865da660b/pacopy/natural.py#L16

?

(Otherwise, `pacopy.natural` is proving very useful for stationary Navier–Stokes work.)

**Comment by nschloe** [comment]
> What about defaulting to no limit as for

Definitely. You can include it in the milestones PR if you want.

**Comment by gdmcbain** [comment]
I was going to add that the change 98d4ccf should also be made in `euler_newton`, for consistency, but I see that it's already there.

https://github.com/nschloe/pacopy/blob/b5ae74c2c17349a04165291e2e74fbc865da660b/pacopy/euler_newton.py#L46
