### ISSUE TITLE
version bump for pacopy.natural.milestones

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pacopy#9]
pacopy.natural.milestones #5 is working nicely but I just realized that it's not yet available with `pip install pacopy` which is still at v. 0.1.0.  

I'd submit a PR but I'm not sure whether it would mean 0.1.1 or 0.2.0.

**Comment by nschloe** [comment]
Let me do it real quick.

**Comment by nschloe** [comment]
Okay, done.
